title: Name of proposed feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before you submit
        Use this template to propose a new feature.

        Ideally, this proposal should be of interest to at least two registered implementations. Implementer interest can also be gathered during the community call that discusses this proposed feature.

        If your implementation has not been previously registered with the [Genomic Knowledge Standards Work Stream](https://ga4gh.github.io/gks.github.io/), please complete the [GKS Product Implementer Form](https://docs.google.com/forms/d/e/1FAIpQLSfVKA6LmeDNYxH7ssnyk0ifRtLCgQKlZfoUzXxzO-h6JkX0og/viewform?usp=sf_link).

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a concise description of the proposed feature.
    validations:
      required: true

  - type: textarea
    id: implementer-support
    attributes:
      label: Supporting implementations
      description: |
        List each implementation interested in this feature, including:
        1. Name of implementation
        2. Name of a contact for the implementation
        3. GitHub handle for the implementation's contact (if available)
        4. Whether they can contribute to the development of this feature (yes or no)
        5. The implementation's priority for the feature as Blocking (0-3 months), Near term (3-12 months), or Future (12+ months) need.

        For example:
          - Implementation name, Daniel Puthawala, @DanielPuthawala, **Can** contribute to the development of this feature, This is a **Near term (3-12 months)** need for this implementation.
          - Implementation name, Brendan Reardon, @brendanreardon, **Cannot** contribute to the development of this feature, This is a **Blocking (0-3 months)** need for this implementation.
    validations:
      required: false

  - type: textarea
    id: justification
    attributes:
      label: Justification and use cases
      description: Why should this feature be developed? Describe the use case(s) that motivate it, ideally with examples from implementers requesting the feature.
    validations:
      required: true

  - type: textarea
    id: current-spec-example
    attributes:
      label: Use cases modeled with the current specification
      description: Show how you would attempt to represent these example categorical variants using the current specification.
    validations:
      required: true

  - type: textarea
    id: current-spec-gap
    attributes:
      label: Gap in the current specification.
      description: Explain the specific limitation or gap in the current specification that this feature would address.
    validations:
      required: true

  - type: textarea
    id: open-questions
    attributes:
      label: Anticipated open questions and design decisions
      description: List questions or design choices that are likely to arise during the development of this feature.
    validations:
      required: false

  - type: input
    id: issue
    attributes:
      label: Associated GitHub Issue
      description: Link to the GitHub Issue for developing this feature, if one exists.
      placeholder: "https://github.com/ga4gh/cat-vrs/issues/01"
    validations:
      required: false

  - type: input
    id: associated-pr
    attributes:
      label: Associated Pull Request
      description: Link to the Pull Request implementing this modification (if already created).
      placeholder: "e.g., https://github.com/ga4gh/cat-vrs/pull/789"
    validations:
      required: false

  - type: textarea
    id: feedback-timeline
    attributes:
      label: Timeline for feedback
      description: "Proposed start and end dates for community feedback. Minimum review period: 1 week after presentation on a community call. _This field is typically completed once review begins of an initial version of this feature_."
      placeholder: |
        Start: 2026-07-01 (community call date)
        End: 2026-07-08
    validations:
      required: false

  - type: checkboxes
    id: development-checklist
    attributes:
      label: Development progress checklist
      description: "Check each item as it is completed during the development process. For more details, see the [GA4GH Technical Specification Development documentation](https://www.ga4gh.org/document/tasc-technical-specification-development/). _This field is typically completed once review begins of an initial version of this feature_."
      options:
        - label: Feature idea discussed on a community call
        - label: Initial draft completed
        - label: Review period started and community notified
        - label: Branch for feature merged
        - label: Specification version incremented and Patch release published
