name: Feature Request
description: Suggest an idea for this project.
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Feature description
      description: Provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Contribution
      description: Can you contribute to the development of this feature?
      options:
        - "Yes, I can create a PR for this feature."
        - "Yes, but I can only provide ideas and feedback."
        - "No, I cannot contribute."
    validations:
      required: false
